### ISSUE TITLE
When using Tasmota with analog output for something other than Vcc the script fails

### ISSUE THREAD

**Issue by bousch** [enesbcs/espfinder-python#3]
Traceback (most recent call last):
  File "espfinder.py", line 237, in <module>
    searchdevices()
  File "espfinder.py", line 171, in searchdevices
    pingscan()
  File "espfinder.py", line 110, in pingscan
    PING_SWEEP(cb_stationsearch,ownip)
  File "espfinder.py", line 31, in __init__
    self.ping_sweeper()
  File "espfinder.py", line 92, in ping_sweeper
    self.callback(1,255)
  File "espfinder.py", line 106, in cb_stationsearch
    analyzerange()
  File "espfinder.py", line 131, in analyzerange
    analyzeip(hostadr)
  File "espfinder.py", line 153, in analyzeip
    tinfos = get_tasmota(par1)
  File "/var/jenkins_home/workspace/espfinder/ef_net.py", line 330, in get_tasmota
    resarr[8] = str(list['StatusSTS']['Vcc'])+"V"
KeyError: 'Vcc'

**Comment by enesbcs** [comment]
Which Tasmota version and which language? I see that in German version all letters are capital "VCC". Can you provide me the output of your "http://ipaddress/cm?cmnd=status%2011""?

**Comment by enesbcs** [comment]
Fixed
